# **SME0142 - Álgebra Linear e Aplicações**
Docente: Cynthia de Oliveira Lage Ferreira


# **Trabalho Prático**
Outubro de 2025

# Alunos: Daniel Jorge Manzano & Nicolas Amaral dos Santos

# Orientações Gerais

*   Esta avaliação é **individual ou em dupla** e deverá ser desenvolvida na plataforma Colab (https://colab.research.google.com/).

*   Cada aluno/dupla deverá produzir um arquivo .ipynb contendo as soluções dos exercícios. Sejam organizados !

*   Os arquivos deverão estar identificados por **NOMEDOALUNO1NoUSP-NOMEDOALUNO2NoUSP.ipynb** a fim de facilitar a organização das atividades pela professora.

*  Os arquivos deverão ser enviados **até às 20h do dia 18/10/2025** através da plataforma e-disciplinas da USP (https://edisciplinas.usp.br/). **Os arquivos recebidos por e-mail não serão corrigidos.** Arquivos enviados fora do prazo também não serão corrigidos!

*   Apenas os alunos que estiverem com a **situação regularizada no Sistema Jupiter** terão suas avaliações corrigidas.

*  Todos os códigos utilizados para resolver os problemas deverão ser apresentados, executados e minimamente comentados. **Questões com respostas sem justificativas não serão consideradas.**

**BOM TRABALHO!**

In [27]:
#Bibliotecas Utilizadas
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import pandas as pd

# **Exercício 1**
Considere o espaço vetorial real $\mathbb{R}^2$. Sejam as transformações
- $T_1:\mathbb{R}^2 \to \mathbb{R}^2$ tal que $T_1(x,y)=(-x,y)$ - **reflexão em torno do eixo $oy$**;
- $T_2:\mathbb{R}^2 \to \mathbb{R}^2$ tal que a matriz da transformação é dada por
$$[T_2] = \begin{bmatrix} 1 & k \\ 0 & 1 \end{bmatrix},$$
com $k\in\mathbb{R}$ - **cisalhamento horizontal**.

a) Aplique as transformações $T_1$ e $T_2$ no quadrado de vértices $(0,0)$, $(1,0)$, $(1,1)$ e $(0,1)$ considerando o parâmetro $k= -0,5$ e visualize os resultados.

b) Determine a matriz da transformação $T_3$ que primeiro faz um cisalhamento horizontal com $k=-0.5$ mapeando $e_2$ em $e_2 - 0.5e_1$ ($e_1$ se mantém inalterado) e então reflete o resultado em torno do eixo $oy$. **Dica:** Determine a posição final das imagens de $e_1$ e $e_2$.

c) Qual a relação entre as matrizes $[T_1]$, $[T_2]$ e a matriz da transformação $[T_3]$ obtida no item anterior?

d) Determine a transformação de reflexão em torno do eixo $ox$ e a transformação de cisalhamento vertical.

In [28]:
# Código letra A

# Solução 1
# Vértices do quadrado
Q = np.array([[0,0],[1,0],[1,1],[0,1]]).T

# Reflexão em torno do eixo y
# (-x,y) = x(-1,0) + y(0,1)
T1 = np.array([[-1, 0], [0, 1]])

# Cisalhamento horizontal k = -0.5
k = -0.5
T2 = np.array([[1, k], [0, 1]])

# Aplicando as transformações
T1Q = T1 @ Q
T2Q = T1 @ Q

def plotSimples(vx, vy):
  plt.figure(figsize=(6,6))
  plt.axis([-2, 2, -2, 2])
  plt.plot([-2,2], [0,0], 'k--', alpha=0.75)
  plt.plot([0,0], [-2,2],'k--', alpha=0.75)
  plt.plot(vx, vy, 'k')
  plt.plot([vx[0], vx[-1]], [vy[0], vy[-1]], 'k')
  plt.plot(vx, vy, 'bo')
  plt.grid(True)

# Plots (para ver o plot no próprio notebook, comentar as linhas com "plt.close()"; por padrão, eles são salvos e não aparecem no notebook)
plotSimples(Q[0,:], Q[1,:])
plt.title('Vértices originais')
plt.savefig("1a_vertices_originais.png")
plt.close()

plotSimples(T1Q[0,:], T1Q[1,:])
plt.title('Reflexão')
plt.savefig("1a_reflexao.png")
plt.close()

plotSimples(T2Q[0,:], T2Q[1,:])
plt.title('Cisalhamento')
plt.savefig("1a_cisalhamento.png")
plt.close()

In [29]:
# Código letra B

#Solução 2)
# Observando as posições finais de e1 e e2 temos:
# T3(1,0) = (-1,0)
# T3(0,1) = (0.5,1)
T3 = np.array([[-1, 0.5], [0, 1]])
print("--- Solução 2 ---")
print("Matriz T3 encontrada pela observação dos vetores da base:")
print(T3)

# Código letra C

# Solução 3)
# Por outro lado, aplicando T2, depois T1
print("\n--- Solução 3 ---")
print("Verificando T3 pelo produto T1 @ T2:")
T1_vezes_T2 = T1 @ T2
print(T1_vezes_T2)
print("Os resultados são iguais, como esperado.")

# Código letra D

# Solução 4)
# Reflexão em torno do eixo x
T4 = np.array([[1, 0], [0, 1]])

# Cisalhamento vertical: (x, y) -> (x, y + kx) com k = -0.5
T5 = np.array([[1, 0], [-0.5, 1]])

# Aplicando as transformações
T4Q = T4 @ Q
T5Q = T5 @ Q

# Plots (assim como os plots anteriores, comentar as linhas com "plt.close()" para ver o plot no notebook)
plotSimples(T4Q[0,:], T4Q[1,:])
plt.title('Reflexão em x')
plt.savefig("1d_reflexao_x.png")
plt.close()

plotSimples(T5Q[0,:], T5Q[1,:])
plt.title('Cisalhamento vertical')
plt.savefig("1d_cisalhamento_vertical.png")
plt.close()


--- Solução 2 ---
Matriz T3 encontrada pela observação dos vetores da base:
[[-1.   0.5]
 [ 0.   1. ]]

--- Solução 3 ---
Verificando T3 pelo produto T1 @ T2:
[[-1.   0.5]
 [ 0.   1. ]]
Os resultados são iguais, como esperado.


# **Exercício 2**
Considere a transformação $T:R^7 \rightarrow R^3$ linear dada pela matriz

$$
\left(\begin{array}{ccccccc}
3 & 9 & 6 & 6 & 9 & 3 & 1\\
2 & 0 & 9 & 2 & 0 & 5 & 3\\
0 & 0 & 1 & 0 & 1 & 0 & 2
\end{array}\right)
$$

a) Qual a dimensão do núcleo e da imagem da transformação? Faça um código para determinar a dimensão da imagem e conclua, então, a dimensão do núcleo.

b) Encontre uma base para o espaço núcleo.

c) Faça um código para verificar que a base encontrada está gerando o núcleo.

In [30]:
B = np.asarray([[3, 9, 6, 6, 9, 3, 1],
                [2, 0, 9, 2, 0, 5, 3],
                [0, 0, 1 , 0, 1, 0, 2]])


# a) ----------------------- //
print("QUESTÃO A ----")

# calcular a dimensão da imagem
dim_imagem = np.linalg.matrix_rank(B)
print(f"Dimensão da imagem: {dim_imagem}")

# sabendo que dim(domínio) = dim(imagem) + dim(núcleo), calculamos, também, a dimensão do núcleo
dim_nucleo = B.shape[1] - dim_imagem # 'B.shape[1]' nos dá o número de colunas
print(f"Dimensão do núcleo: {dim_nucleo}")


# b) ----------------------- //
print("\nQUESTÃO B ----")

import sympy as sp # para não recorrer a métodos numéricos (usando numpy) podemos usar o sympy

B_sp = sp.Matrix(B) # converte B para o formato do sympy. usamos para aplicar o .nullspace(), que encontra os vetores da base do núcleo
base_nucleo = B_sp.nullspace() 
print("Base do núcleo:")
sp.pprint(base_nucleo)


# c) ----------------------- //
print("\nQUESTÃO C ----")

# para verificar se a base encontrada gera o núcleo, devemos:
# 1. verificar se cada vetor da base, quando multiplicamos pela matriz B, resulta no vetor nulo
# 2. verificar se os vetores são linearmente independentes

# 1. aplica-se o np.allclose (comparando com um vetor nulo como resultado) sobre cada vetor da base para verificar se B @ v = 0
pertencem_ao_nucleo = [np.allclose(B @ np.array(v).astype(np.float64), np.zeros(B.shape[0])) for v in base_nucleo]
print("Os vetores da base pertencem ao núcleo?", all(pertencem_ao_nucleo))

# 2. verifica-se a independência linear calculando a dimensão da base do núcleo (converte a matriz para o formato numpy e calcula numericamente)
matriz_base = np.array(base_nucleo).astype(np.float64).reshape(len(base_nucleo), -1)
rank_base = np.linalg.matrix_rank(matriz_base)
sao_li = (rank_base == len(base_nucleo)) # se a dimensão é igual ao número de vetores, são LI
print("Os vetores da base são linearmente independentes?", sao_li)

if (all(pertencem_ao_nucleo) & sao_li): print("Portanto, a base encontrada gera o núcleo.")

QUESTÃO A ----
Dimensão da imagem: 3
Dimensão do núcleo: 4

QUESTÃO B ----
Base do núcleo:
⎡                         ⎡15/2⎤⎤
⎢⎡ -1 ⎤  ⎡ 9/2 ⎤  ⎡-5/2⎤  ⎢    ⎥⎥
⎢⎢    ⎥  ⎢     ⎥  ⎢    ⎥  ⎢-23 ⎥⎥
⎢⎢-1/3⎥  ⎢-11/6⎥  ⎢1/2 ⎥  ⎢────⎥⎥
⎢⎢    ⎥  ⎢     ⎥  ⎢    ⎥  ⎢ 18 ⎥⎥
⎢⎢ 0  ⎥  ⎢ -1  ⎥  ⎢ 0  ⎥  ⎢    ⎥⎥
⎢⎢    ⎥  ⎢     ⎥  ⎢    ⎥  ⎢ -2 ⎥⎥
⎢⎢ 1  ⎥, ⎢  0  ⎥, ⎢ 0  ⎥, ⎢    ⎥⎥
⎢⎢    ⎥  ⎢     ⎥  ⎢    ⎥  ⎢ 0  ⎥⎥
⎢⎢ 0  ⎥  ⎢  1  ⎥  ⎢ 0  ⎥  ⎢    ⎥⎥
⎢⎢    ⎥  ⎢     ⎥  ⎢    ⎥  ⎢ 0  ⎥⎥
⎢⎢ 0  ⎥  ⎢  0  ⎥  ⎢ 1  ⎥  ⎢    ⎥⎥
⎢⎢    ⎥  ⎢     ⎥  ⎢    ⎥  ⎢ 0  ⎥⎥
⎢⎣ 0  ⎦  ⎣  0  ⎦  ⎣ 0  ⎦  ⎢    ⎥⎥
⎣                         ⎣ 1  ⎦⎦

QUESTÃO C ----
Os vetores da base pertencem ao núcleo? True
Os vetores da base são linearmente independentes? True
Portanto, a base encontrada gera o núcleo.


# **Exercício 3**

a) Dada uma base qualquer de um subespaço vetorial do $R^{n}$, escreva um código para encontrar uma base ortonormal para este subespaço. Teste o seu código para a base dada pelas colunas da matriz  **V**  gerada no código abaixo.

b) Faça um teste para verificar que a base obtida é de fato ortonormal.

In [31]:
V = np.random.randint(0,20,size=(20,10))
print(V)

[[14  5 13  2 18  7 13  0 13 11]
 [19 13  9  5 15  3  3 11 17  4]
 [18  5 17  3  3 13  8 14 10 18]
 [ 0  8 10 18 18 15  1  1  5 13]
 [13  7  0  2 17  0 15  1 10 19]
 [ 9 14  5 13 11 18  9  0 12  6]
 [17  3  8  5  3  7 10 16  8  1]
 [15  0  9 15 19  3 15  8 13  7]
 [ 4  7  1  9 15 13  1 15  8  4]
 [ 4  5 17 10 14 17 15 10  4 18]
 [ 9  7  0  3  9 15 16 11 11  6]
 [ 7  2  2  2  2 17 19  1 16 14]
 [ 2  8 15  5 13  2 15  8  2 10]
 [ 0 16 12  3 17 18  1 13 16 13]
 [10  6 10  5 10  7 10 19 17  5]
 [17  0  1 14  4 10 11 11  1  4]
 [19 17 12 15 14 18  6  2 15 14]
 [19  7  2 10  5  3 17 19 19 19]
 [13  0  2  2 15 18  2 15 12  2]
 [10 16 19 11  4  4 19  9  8 17]]


In [32]:
# a) Ortonormalização de uma base qualquer dada e teste do código em V

def gram_schmidt(A):
    """
    Aplica o processo de ortonormalização de Gram-Schmidt às colunas de uma matriz A.
    Parâmetros: A (np.array): Matriz cujas colunas formam a base a ser ortonormalizada.
    Retorna: Q (np.array): Matriz com colunas ortonormais que formam uma base para o mesmo subespaço.
    """

    # Pega as dimensões da matriz de entrada
    n_linhas, n_cols = A.shape
    
    # Cria uma matriz de zeros para armazenar a base ortonormal resultante (Q)
    Q = np.zeros_like(A, dtype=float)
    
    # Itera sobre cada coluna/vetor da matriz A
    for i in range(n_cols):
        # Pega o vetor v_i atual
        v = A[:, i].astype(float)
        
        # Inicia o processo de ortogonalização: u_i = v_i - proj(v_i) sobre os q_j's anteriores
        # Começamos com u = v e subtraímos as projeções
        u = v.copy()
        for j in range(i):
            q_j = Q[:, j]
            # Coeficiente da projeção de v sobre q_j: (v . q_j)
            # Como q_j já é unitário, não precisamos dividir pela sua norma ao quadrado.
            proj_coeff = np.dot(v, q_j)
            # Subtrai a projeção de u
            u -= proj_coeff * q_j
            
        # Normalização: transforma o vetor ortogonal u em um vetor unitário q
        # Calcula a norma (comprimento) do vetor u
        norma_u = np.linalg.norm(u)
        
        # Evita divisão por zero se o vetor for nulo (o que indica vetores L.D. na entrada)
        if norma_u > 1e-10:
            Q[:, i] = u / norma_u
            
    return Q


# Aplica a função de Gram-Schmidt na matriz V
Q = gram_schmidt(V)

# Imprime o resultado para verificação
print("--- Base Ortonormal Q (Letra a) ---")
print("A matriz resultante tem dimensões:", Q.shape)
print("\nMostrando as primeiras 5 linhas e 5 colunas:")
print(Q[:5, :5])


# b) Teste que verifica se a base obtida é de fato ortonormal

print("--- Verificação da Ortronormalidade (Letra b) ---")

# 1. Calcular o produto da transposta de Q pela própria matriz Q.
QT_Q = Q.T @ Q

print("\nResultado do produto Q.T @ Q:")
# Arredondamos o resultado para 10 casas decimais para facilitar a visualização.
print(np.round(QT_Q, decimals=10))

# 2. Verificar se o resultado é a Matriz Identidade.
# Criamos a matriz identidade do tamanho correto (10x10, pois Q tem 10 colunas).
identidade = np.identity(Q.shape[1])

# allclose retorna True se as matrizes são "suficientemente próximas".
e_ortonormal = np.allclose(QT_Q, identidade)

print(f"\nO resultado do teste np.allclose(QT_Q, Identidade) é: {e_ortonormal}")

# 3. Imprimir uma conclusão clara
if e_ortonormal:
    print("\nConclusão: O teste confirma que a base é ortonormal.")
else:
    print("\nConclusão: O teste falhou. A base NÃO é ortonormal.")

--- Base Ortonormal Q (Letra a) ---
A matriz resultante tem dimensões: (20, 10)

Mostrando as primeiras 5 linhas e 5 colunas:
[[ 0.24783614 -0.05106736  0.24459319 -0.23569611  0.32037856]
 [ 0.33634904  0.13597604 -0.14460016 -0.24725636  0.07384019]
 [ 0.31864646 -0.11284925  0.3616125  -0.2679772  -0.23850212]
 [ 0.          0.26427076  0.16164886  0.54938346  0.16336101]
 [ 0.23013356  0.0304458  -0.27625927 -0.15473069  0.36079699]]
--- Verificação da Ortronormalidade (Letra b) ---

Resultado do produto Q.T @ Q:
[[ 1. -0. -0.  0. -0. -0. -0. -0.  0.  0.]
 [-0.  1.  0.  0.  0. -0.  0.  0.  0. -0.]
 [-0.  0.  1.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  1. -0.  0.  0. -0. -0. -0.]
 [-0.  0.  0. -0.  1. -0. -0.  0.  0. -0.]
 [-0. -0.  0.  0. -0.  1. -0.  0.  0.  0.]
 [-0.  0.  0.  0. -0. -0.  1.  0.  0.  0.]
 [-0.  0.  0. -0.  0.  0.  0.  1.  0. -0.]
 [ 0.  0.  0. -0.  0.  0.  0.  0.  1. -0.]
 [ 0. -0. -0. -0. -0.  0.  0. -0. -0.  1.]]

O resultado do teste np.allclose(QT_Q, Identi

# **Exercício 4**


Considere a seguinte rede não direcionada composta por 12 nós, com conexões definidas pela matriz de adjacência abaixo (os nós estão numerados de 1 a 12).

A rede foi construída com o objetivo de evidenciar a diferença entre duas medidas de centralidade: **centralidade de grau** e **centralidade de autovalor**.

### **Matriz de Adjacência**

A matriz a seguir é referente a rede considerada. Um valor $1$ na posição $(i,j)$ indica uma conexão entre os nós $i$ e $j$; $0$ indica ausência de conexão.



A =
\begin{bmatrix}
0 & 1 & 1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 0 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
1 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
\end{bmatrix}







Com base na estrutura da rede acima, realize as seguintes tarefas:

    

a)   Calcule a centralidade de grau para cada nó. Liste os nós com maior centralidade de grau.

b)   Calcule a centralidade de autovalor para cada nó. Liste os nós com maior centralidade de autovalor.

c)   Há nós com alta centralidade de grau mas baixa centralidade de autovalor? Justifique com base na estrutura da rede.


d)   Há nós com baixa centralidade de grau mas alta centralidade de autovalor? Explique o motivo.

e)   Discuta as diferenças entre as duas centralidades à luz dos resultados obtidos.




    
    
    
    













In [33]:
A = np.array([
    [0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
])

# Criar o grafo
G_temp = nx.from_numpy_array(A) # Grafo temporário a partir da matriz A
G = nx.relabel_nodes(G_temp, {i: i + 1 for i in range(12)}) # Renomeia os nós de 0-11 para 1-12, criando o grafo final G

# Código letras A e B: Cálculo e listagem das centralidades

# Calcular centralidades
deg_centrality = nx.degree_centrality(G) # # Calcula a centralidade de grau para todos os nós do grafo G
eig_centrality = nx.eigenvector_centrality(G, max_iter=1000) # Calcula a centralidade de autovalor para todos os nós

# Exibir tabela com os valores calculados para cada nó
centrality_df = pd.DataFrame({
    "Grau": deg_centrality,
    "Autovalor": eig_centrality
}).sort_index().round(4)


print("--- Respostas para (a) e (b) ---")
print("Centralidades dos nós:\n")
print(centrality_df)

# Visualizar o grafo
plt.figure(figsize=(10, 10))
pos = nx.spring_layout(G, seed=42)
node_sizes = [v * 5000 for v in deg_centrality.values()]
node_colors = list(eig_centrality.values())

nodes = nx.draw_networkx_nodes(G, pos, node_size=node_sizes, node_color=node_colors, cmap=plt.cm.viridis)

nx.draw_networkx_edges(G, pos, alpha=0.6)
nx.draw_networkx_labels(G, pos, font_color='white', font_weight='bold')

plt.title("Rede: Tamanho por Grau, Cor por Autovalor")

cbar = plt.colorbar(nodes)

cbar.set_label("Centralidade de Autovalor", rotation=270, labelpad=15)

plt.savefig("4ab_grafo_centralidades.png")
plt.close() # para visualizar o grafo no notebook, comentar esta linha

"""
Letras C, D, E: Justificativas e Discussão

C) Há nós com alta centralidade de grau mas baixa centralidade de autovalor?

Não. Nesta rede, os nós com alta centralidade de grau (nós 1 a 6) são também os que possuem os maiores valores de centralidade de autovalor.
Justificativa: Os nós de 1 a 5 formam um grupo densamente conectado (clique) e estão ligados ao nó 6, que é a ponte para o resto da rede.
O nó 6, por sua vez, possui o maior número de conexões. Devido a essa estrutura, todos os nós com muitas conexões são, por definição, influentes 
e bem posicionados, resultando também em alta centralidade de autovalor.

-----------------------------------------------------------------------------------------------------------------------------------------------------------

D) Há nós com baixa centralidade de grau mas alta centralidade de autovalor?

Sim. Os nós de 7 a 12 se encaixam perfeitamente nesta descrição.
Motivo: Cada um desses nós possui o menor grau possível na rede (grau 1), o que resulta em uma centralidade de grau muito baixa. 
No entanto, a única conexão que eles possuem é com o nó 6, que é o nó mais influente e central de toda a rede. 
Ao estarem conectados a um nó tão importante, eles "herdam" parte dessa influência, o que eleva sua centralidade de autovalor a um nível
consideravelmente mais alto do que seu baixo grau sugeriria.

-----------------------------------------------------------------------------------------------------------------------------------------------------------

E) Discuta as diferenças entre as duas centralidades à luz dos resultados obtidos.

Os resultados desta rede evidenciam a diferença fundamental entre as duas métricas:

- Centralidade de Grau: É uma medida de popularidade local, simplesmente contando o NÚMERO de conexões diretas. O nó 6 é o vencedor claro com 7 conexões, 
enquanto os nós 7-12 são os "perdedores" com apenas 1 conexão cada.

- Centralidade de Autovalor: É uma medida de influência, que considera a QUALIDADE das conexões. Ela responde à pergunta "quão importantes são seus vizinhos?".
O nó 6 é o mais influente por conectar os dois principais agrupamentos da rede. Os nós 7-12, apesar de terem poucas conexões, demonstram uma influência significativa (autovalor de ~0.24)
porque estão ligados ao nó mais importante.
Em resumo, o exercício mostra que um nó não precisa ter muitas conexões para ser influente, desde que suas poucas conexões sejam com os nós certos.
"""


--- Respostas para (a) e (b) ---
Centralidades dos nós:

      Grau  Autovalor
1   0.4545     0.3976
2   0.4545     0.3976
3   0.4545     0.3976
4   0.4545     0.3976
5   0.5455     0.3944
6   0.9091     0.4141
7   0.0909     0.0823
8   0.0909     0.0823
9   0.0909     0.0823
10  0.0909     0.0823
11  0.0909     0.0823
12  0.0909     0.0823


'\nLetras C, D, E: Justificativas e Discussão\n\nC) Há nós com alta centralidade de grau mas baixa centralidade de autovalor?\n\nNão. Nesta rede, os nós com alta centralidade de grau (nós 1 a 6) são também os que possuem os maiores valores de centralidade de autovalor.\nJustificativa: Os nós de 1 a 5 formam um grupo densamente conectado (clique) e estão ligados ao nó 6, que é a ponte para o resto da rede.\nO nó 6, por sua vez, possui o maior número de conexões. Devido a essa estrutura, todos os nós com muitas conexões são, por definição, influentes \ne bem posicionados, resultando também em alta centralidade de autovalor.\n\n-----------------------------------------------------------------------------------------------------------------------------------------------------------\n\nD) Há nós com baixa centralidade de grau mas alta centralidade de autovalor?\n\nSim. Os nós de 7 a 12 se encaixam perfeitamente nesta descrição.\nMotivo: Cada um desses nós possui o menor grau possível na red

# **Exerício 5**

Em um cenário onde um analista de dados possui uma coleção de documentos textuais de natureza variada — como notícias, publicações em redes sociais, ou descrições de produtos —, surge a necessidade de identificar automaticamente os **principais temas ou tópicos** abordados nesses textos. Tal tarefa é especialmente relevante em contextos onde os dados são não rotulados e o volume de documentos inviabiliza a análise manual.


**Objetivo:**
Dado um conjunto de 10 manchetes de notícias, aplicar **Análise Semântica Latente (LSA) via SVD** para identificar **temas comuns** (conceitos latentes) e analisar a relevância de palavras e documentos.

---

# **Conjunto de manchetes**

1. Time vence campeonato nacional
2. Jogador é destaque na vitória do time
3. Equipe perde final em jogo equilibrado
4. Treinador elogia desempenho da equipe
5. Jogador marca gol decisivo no campeonato
6. Time reage e vence partida importante
7. Jogador lidera equipe rumo à final
8. Equipe conquista vitória histórica
9. Treinador anuncia substituição estratégica
10. Jogador decide jogo com gol de empate
11. Bolsa de valores sobe após anúncio econômico
12. Mercado financeiro reage a nova política fiscal
13. Inflação preocupa investidores e governo
14. Governo anuncia medidas para controlar inflação
15. Mercado de ações fecha em alta
16. Valores da bolsa aumentam com relatório positivo
17. Investidores reagem à decisão do banco central
18. Política econômica impacta mercado financeiro
19. Inflação e desemprego influenciam investidores
20. Governo divulga plano fiscal detalhado



**Procedimento matemático**

 **Representação:**

   * Construir uma **matriz termo-documento** $A \in \mathbb{R}^{m \times 10}$, com linhas correspondendo a **palavras relevantes** (substantivos e verbos de ação) e colunas aos documentos.
   * Cada elemento $a_{ij}$ indica a presença ou frequência da palavra $i$ no documento $j$.

 **Decomposição SVD:**
   $
   A = U  \Sigma  V^T
   $

   * $U \in \mathbb{R}^{m \times r}$: indica a participação das palavras nos conceitos latentes
   * $\Sigma \in \mathbb{R}^{r \times r}$: indica a importância de cada conceito
   * $V \in \mathbb{R}^{10 \times r}$: indica a participação dos documentos nos conceitos latentes
   * $r = \text{posto}(A)$


a) Qual é o tema dominante no conjunto de manchetes? Qual é secundário?

b) Quais palavras (substantivos ou verbos) são mais representativas de cada tema? Liste 5 de cada.

c) Quais são os 5 documentos mais representativas de cada tema?

d) Como os verbos de ação contribuiram para a distinção entre os temas?




In [34]:
# LSA com SVD em 20 manchetes, vocabulário único e verbos de ação
from sklearn.feature_extraction.text import CountVectorizer # você pode usar esta função para montar a matriz termo-documento
from sklearn.decomposition import TruncatedSVD


# Conjunto de 20 manchetes
documents = [
    # Esportes
    "Time vence campeonato nacional",
    "Jogador é destaque na vitória do time",
    "Equipe perde final em jogo equilibrado",
    "Treinador elogia desempenho da equipe",
    "Jogador marca gol decisivo no campeonato",
    "Time reage e vence partida importante",
    "Jogador lidera equipe rumo à final",
    "Equipe conquista vitória histórica",
    "Treinador anuncia substituição estratégica",
    "Jogador decide jogo com gol de empate",
    # Economia
    "Bolsa de valores sobe após anúncio econômico",
    "Mercado financeiro reage a nova política fiscal",
    "Inflação preocupa investidores e governo",
    "Governo anuncia medidas para controlar inflação",
    "Mercado de ações fecha em alta",
    "Valores da bolsa aumentam com relatório positivo",
    "Investidores reagem à decisão do banco central",
    "Política econômica impacta mercado financeiro",
    "Inflação e desemprego influenciam investidores",
    "Governo divulga plano fiscal detalhado"
]

# Vocabulário restrito a palavras-chave (substantivos + verbos de ação), sem duplicatas
vocabulary = [
    # Esportes
    "time", "jogador", "campeonato", "vitória", "equipe", "final", "jogo", "treinador", "gol",
    "vence", "marca", "perde", "reage", "decide", "conquista", "anuncia", "lidera", "substituição",
    # Economia
    "bolsa", "valores", "mercado", "financeiro", "inflação", "investidores", "governo",
    "sobe", "preocupa", "divulga", "impacta", "aumentam", "decisão", "plano"
]

#Matriz termo-documento (contagem simples)

# Aplicar SVD (LSA)
k = 2  # número de temas latentes

# Palavras mais importantes por tema
n_top_words = 5

# Documentos mais associados a cada tema
n_top_docs = 5


# acima, código predefinido pelo exercício. abaixo, nossa lógica de solução --------------------------------------------------------------------


# inicializa 'CountVectorizer' com o vocabulário dado; cada linha representa uma palavra do vocabulário, cada coluna representa um documento (manchete)
# 'vocabulary=vocabulary': Garante que apenas as palavras da lista sejam consideradas (o primeiro 'vocabulary' é o parâmetro do CountVectorizer)
# 'binary=True': Faz com que a contagem seja 0 ou 1 (presente ou ausente), em vez de contar múltiplas ocorrências
vectorizer = CountVectorizer(vocabulary=vocabulary, binary=True)

# ".fit_transform()" aprende o vocabulário e transforma os documentos na matriz A
A = vectorizer.fit_transform(documents).toarray().T # usamos .T para ter palavras nas linhas e docs nas colunas
# print(A) # descomentar para ver a matriz

# inicializamos o modelo SVD para encontrar k temas ("TruncatedSVD" é uma versão eficiente do SVD, boa para LSA) 
svd = TruncatedSVD(n_components=k, random_state=0) # setar "random_state" fixo garante reprodutibilidade (mantém o mesmo resultado sempre). coloquei 0 por nada em particular

# aplicamos o SVD na nossa matriz A; o resultado que nos interessa para os documentos fica no transform
# ".fit()" aprende a decomposição (U, Sigma, V^T), ".transform()" aplica a decomposição aos dados
matriz_documento_tema = svd.fit_transform(A.T) # a entrada deve ser (documentos, palavras), por isso .T no A

# cria rótulos para os temas com base nas palavras mais importantes. usado posteriormente para interpretar os temas e imprimir resultados
feature_names = vectorizer.get_feature_names_out()
theme_labels = [] # lista para guardar rótulos que serão criados
for i, topic in enumerate(svd.components_):
    top_words_indices = topic.argsort()[::-1][:n_top_words]
    top_words = [feature_names[idx] for idx in top_words_indices]
    # cria um rótulo para o tema com base em suas 3 palavras principais
    label = f"'{top_words[0].capitalize()}'"
    theme_labels.append(label)

# a) ----------------------- //
print("\nQUESTÃO A ----")
# svd.explained_variance_ dá uma medida da importância de cada tema
importancia_temas = svd.explained_variance_

# identifica qual índice (0 ou 1) tem a maior importância
idx_dominante = np.argmax(importancia_temas)
idx_secundario = np.argmin(importancia_temas)

print(f"Tema Dominante: {theme_labels[idx_dominante]}")
print(f"  - Importância (explained variance): {importancia_temas[idx_dominante]:.2f}")

print(f"Tema Secundário: {theme_labels[idx_secundario]}")
print(f"  - Importância (explained variance): {importancia_temas[idx_secundario]:.2f}\n")

# b) ----------------------- //
print("\nQUESTÃO B ----")

for i, label in enumerate(theme_labels):
    # reutiliza a lógica anterior para pegar as 5 palavras (n_top_words) associadas ao tema
    topic = svd.components_[i]
    top_words_indices = topic.argsort()[::-1][:n_top_words]
    top_words = [feature_names[idx] for idx in top_words_indices]
    print(f"Palavras associadas ao tema {label}: {', '.join(top_words)}")
print()

# c) ----------------------- //
print("\nQUESTÃO C ----")
# para cada tema (coluna da matriz_documento_tema), encontra os índices dos documentos (linhas) com os maiores valores
for i, label in enumerate(theme_labels):
    # .argsort()[::-1] ordena os índices dos documentos do mais relevante para o menos relevante
    top_docs_indices = matriz_documento_tema[:, i].argsort()[::-1][:n_top_docs]
    print(f"Documentos mais representativos do tema {label}:")
    for doc_idx in top_docs_indices:
        print(f"  - (Doc {doc_idx+1}) {documents[doc_idx]}")
print()

# d) ----------------------- //
print("\nQUESTÃO D ----")
print("Os verbos de ação foram fundamentais para a distinção clara entre os temas.")
print("A associação semântica entre substantivos pode ser ambígua, mas a combinação de certos pares verbo-substantivo mostram claramente a existência de um certo tema associado.")
print("Por exemplo, 'time/vence' e 'jogador/marca' são fortemente ligados ao tema esportivo, enquanto 'bolsa/sobe' e 'governo/anuncia' são claramente econômicos, o que provavelmente seria menos evidente numa análise baseada apenas em substantivos ou verbos.")



QUESTÃO A ----
Tema Dominante: 'Inflação'
  - Importância (explained variance): 0.28
Tema Secundário: 'Jogador'
  - Importância (explained variance): 0.26


QUESTÃO B ----
Palavras associadas ao tema 'Jogador': jogador, equipe, final, gol, jogo
Palavras associadas ao tema 'Inflação': inflação, governo, investidores, preocupa, anuncia


QUESTÃO C ----
Documentos mais representativos do tema 'Jogador':
  - (Doc 7) Jogador lidera equipe rumo à final
  - (Doc 10) Jogador decide jogo com gol de empate
  - (Doc 5) Jogador marca gol decisivo no campeonato
  - (Doc 3) Equipe perde final em jogo equilibrado
  - (Doc 2) Jogador é destaque na vitória do time
Documentos mais representativos do tema 'Inflação':
  - (Doc 13) Inflação preocupa investidores e governo
  - (Doc 14) Governo anuncia medidas para controlar inflação
  - (Doc 19) Inflação e desemprego influenciam investidores
  - (Doc 20) Governo divulga plano fiscal detalhado
  - (Doc 17) Investidores reagem à decisão do banco central


QU