**Exercício 01**

Construa o operador linear diagonalizável $T:\mathbb{R}^3 \to \mathbb{R}^3$ que tenha $2$ e $9$ como autovalores de modo que os autoespaços sejam $V(2) = [(1,2,0),(0,6,1)]$ e $V(9) = [(1,1,1)]$.

In [ ]:
import numpy as np

# autovetores
v1 = np.array([1, 2, 0])
v2 = np.array([0, 6, 1]) # v1 e v2 pertencem a V(2)
v3 = np.array([1, 1, 1]) # v3 pertence a V(9)

# autovalores
lambda1 = 2
lambda2 = 9

# matriz P com autovetores nas colunas
P = np.array([v1, v2, v3]).T

print("--- matriz P (autovetores nas colunas):")
print(P)

# matriz diagonal D com autovalores na diagonal
D = np.diag([lambda1, lambda1, lambda2]) # lambda1=2, lambda1=2, lambda2=9

print("\n--- matriz diagonal D (autovalores):")
print(D)

# calcula matriz M = P * D
M = P @ D

print("\n--- matriz M = P * D:")
print(M)

# resolver a equação P^T * A^T = M^T para as linhas de A
PT = P.T
MT = M.T

# resolve um sistema para cada coluna de A^T (que são as linhas de A)
linhas_de_A = []
for i in range(MT.shape[1]):
    # pega a i-ésima coluna de M^T como o vetor de resultado
    vetor_res = MT[:, i]
    
    # resolve P^T * x = vetor_res, onde x será a i-ésima linha de A
    linha = np.linalg.solve(PT, vetor_res)
    linhas_de_A.append(linha)

# monta a matriz A a partir dos valores calculados
A = np.array(linhas_de_A)

print("\n--- matriz A do Operador T (calculada via sistemas lineares):")
print(A)

# verificação
print("\n--- verificando a solução ---")
check1 = np.allclose(A @ v1, lambda1 * v1)
check2 = np.allclose(A @ v2, lambda1 * v2)
check3 = np.allclose(A @ v3, lambda2 * v3)
print(f"as condições A*v = lambda*v foram satisfeitas? {check1 and check2 and check3}")


--- matriz P (autovetores nas colunas):
[[1 0 1]
 [2 6 1]
 [0 1 1]]

--- matriz diagonal D (autovalores):
[[2 0 0]
 [0 2 0]
 [0 0 9]]

--- matriz M = P * D:
[[ 2  0  9]
 [ 4 12  9]
 [ 0  2  9]]

--- matriz A do Operador T (calculada via sistemas lineares):
[[ 4. -1.  6.]
 [ 2.  1.  6.]
 [ 2. -1.  8.]]

--- Verificando a solução ---
As condições A*v = lambda*v foram satisfeitas? True


**Exercício 02**

Construa uma transformação linear que mapeia o vetor $\mathbf{v}=[1,1,1,1,1]\in\mathbb{R}^5$ nele mesmo, ou seja, a transformação deve satisfazer $\mathbf{A}\mathbf{v}=\mathbf{v}$.

In [2]:
# vetor v
v = np.ones(5) 

# constrói a matriz identidade A 
A1 = np.eye(5)
print("matriz A1:\n", A1)

# verificacão
resultado = A1 @ v
print("\nresultado de A1 * v:", resultado)
print("a condição A*v = v é satisfeita?", np.allclose(resultado, v))

matriz A1:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

resultado de A1 * v: [1. 1. 1. 1. 1.]
a condição A*v = v é satisfeita? True
