

---

##  Isometrias no Plano via Matrizes

### **Objetivo**

Explorar as principais **isometrias no plano**  — **rotação**, **reflexão**, **translação** e **composições** — utilizando **representações matriciais** e verificando suas propriedades geométricas por meio de código e visualização gráfica.

---



Considere o triângulo  $ABC$ , com vértices definidos por:

*  A = (1, 1)
*  B = (3, 1)
*  C = (2, 3)

Represente o triângulo como uma matriz, onde cada **coluna** é um ponto:


T=
$\begin{bmatrix}
1 & 3 & 2 \\
1 & 1 & 3
\end{bmatrix}$



 Escreva as **matrizes** das seguintes transformações:

   a) **Reflexão** em relação ao eixo $x$

   b) **Reflexão** em relação à reta $y = x$

   c) **Rotação** no sentido anti-horário em torno da origem por um ângulo genérico $\theta$ (em graus)

Dica: use a fórmula

  $R_\theta = $ $$
\begin{bmatrix}
\cos(\theta) & -\sin(\theta) \\
\sin(\theta) & \cos(\theta)
\end{bmatrix} $$

  

   d) **Translação** pelo vetor $ \vec{v} = (2, -1) $

---

##  Aplicações Diretas

 Aplique **individualmente** cada transformação ao triângulo $T$, utilizando:

 Multiplicação de matrizes $T' = A \cdot T$, para isometrias lineares e soma vetorial $T' = A \cdot T + \vec{v}$, quando houver translação

 Visualize (graficamente) o triângulo original e cada triângulo transformado.

---
 Composição de Isometrias

 Considere a seguinte composição de transformações:

   * Primeiro: **rotação** de $\theta = 90^\circ$
   * Depois: **reflexão** no eixo $x$

   a) Escreva a **matriz composta** $M = R_x \cdot R_{90}$

   b) Aplique $M$ ao triângulo $T$ e visualize o resultado.

   c) Interprete geometricamente o efeito da transformação composta. O que ela faz com o triângulo?

 Escolha um valor arbitrário de $\theta$ (por exemplo, $45^\circ$) e repita os passos acima.



# Análise Geométrica

 Após cada isometria ou composição:

   a) As **distâncias** entre os vértices são preservadas?

   b) Os **ângulos** internos permanecem os mesmos?

   Justifique com código ou cálculo. Lembre-se: **isometrias preservam distâncias e ângulos**.

---

##  Desafio Extra

 Implemente uma função que recebe:

   * Um conjunto de pontos $P$
   * Um tipo de isometria
   * Parâmetros (ângulo, vetor de translação, etc.)

   E retorna a imagem transformada $P'$. Use essa função para aplicar sequências arbitrárias de transformações ao triângulo.


##  Matrizes úteis para referência

* **Reflexão sobre o eixo $x$:**
  
 $ R_x = $
  $\begin{bmatrix}
  1 & 0 \\
  0 & -1
  \end{bmatrix}
  $

* **Reflexão na reta $y = x$:**
 $
  R_{y=x} = $
  $\begin{bmatrix}
  0 & 1 \\
  1 & 0
  \end{bmatrix}
  $

* **Rotação de $\theta$ graus anti-horária:**
 $
  R_\theta =$
 $ \begin{bmatrix}
  \cos \theta & -\sin \theta \\
  \sin \theta & \cos \theta
  \end{bmatrix}
  $

* **Translação por vetor $\vec{v} = (a, b)$:**
  $
  T(\vec{x}) = \vec{x} + \vec{v}
  $



In [ ]:
import numpy as np
import matplotlib.pyplot as plt

"""
definições iniciais ----------------------------------------------------------------------------------------------------------------------------
"""
# matriz do triângulo T (colunas = pontos A, B, C)
T_orig = np.array([
    [1, 3, 2],  # coordenadas x
    [1, 1, 3]   # coordenadas y
])

# para plotagem, fecha o triângulo (implementado pela função hstack abaixo)
T_plot_orig = np.hstack((T_orig, T_orig[:, 0].reshape(2, 1))) 

"""
matrizes transformação -------------------------------------------------------------------------------------------------------------------------
"""
# a) reflexão no eixo x
R_x = np.array([[1, 0], [0, -1]])

# b) reflexão na reta y = x
R_y_x = np.array([[0, 1], [1, 0]])

# c) rotação (função para criar a matriz a partir de theta)
def matriz_de_rotacao(theta_graus):
    theta_rad = np.deg2rad(theta_graus)
    cos_t = np.cos(theta_rad)
    sin_t = np.sin(theta_rad)
    return np.array([
        [cos_t, -sin_t],
        [sin_t, cos_t]
    ])

# d) translação pelo vetor v = (2, -1)
v_trans = np.array([[2], [-1]])

print("--- Matrizes de Transformação ---")
print(f"R_x:\n{R_x}")
print(f"R_y_x:\n{R_y_x}")
print(f"Vetor Translação v:\n{v_trans.T}\n")

"""
aplicações e visualizações ---------------------------------------------------------------------------------------------------------------------
"""
# função para plotar o triângulo original e o transformado
def plot_simples(T_orig, T_trans, titulo, nome, label_trans='Transformado'):
    T_trans_plot = np.hstack((T_trans, T_trans[:, 0].reshape(2, 1)))
    plt.figure(figsize=(5, 5))
    
    plt.plot(T_orig[0, :], T_orig[1, :], 'k--', label='Original', alpha=0.5)
    plt.plot(T_trans_plot[0, :], T_trans_plot[1, :], 'r-', label=label_trans)

    plt.axhline(0, color='gray', linewidth=0.5)
    plt.axvline(0, color='gray', linewidth=0.5)
    plt.title(titulo)
    plt.axis('equal')
    plt.legend()
    plt.grid(linestyle=':', alpha=0.6)
    plt.savefig(nome)
    plt.close()

# a) reflexão no eixo x
T_Rx = R_x @ T_orig
plot_simples(T_plot_orig, T_Rx, "1. Reflexão no Eixo X", "reflexao_eixo_x.png")

# b) reflexão na reta y = x
T_Ry_x = R_y_x @ T_orig
plot_simples(T_plot_orig, T_Ry_x, "2. Reflexão na Reta y = x", "reflexao_y=x.png")

# c) rotação 90 graus
theta_rot = 90
R_90 = matriz_de_rotacao(theta_rot)
T_R90 = R_90 @ T_orig
plot_simples(T_plot_orig, T_R90, f"3. Rotação {theta_rot}° Anti-horária", "rotacao.png")

# d) translação por v
V_matrix = np.tile(v_trans, T_orig.shape[1])
T_Tv = T_orig + V_matrix
plot_simples(T_plot_orig, T_Tv, "4. Translação por (2, -1)", "translacao.png")

"""
composições de isometrias ----------------------------------------------------------------------------------------------------------------------
"""
# composição 1: rotação 90° (R_90), depois reflexão no eixo x (R_x)
# matriz composta M = R_x @ R_90
M_comp_90 = R_x @ R_90
T_comp_90 = M_comp_90 @ T_orig

print("--- Composição de Isometrias ---")
print(f"Matriz Composta M (R_x @ R_90°):\n{M_comp_90.round(5)}")

plot_simples(T_plot_orig, T_comp_90, "5. Composição (Rot 90° seguido de Refl Eixo X)", 
            "rot90_refl_x.png", label_trans="Rot 90° + Refl X")

# composição 2: escolha arbitrária (theta = 45°)
R_45 = matriz_de_rotacao(45)
M_comp_45 = R_x @ R_45
T_comp_45 = M_comp_45 @ T_orig

plot_simples(T_plot_orig, T_comp_45, "6. Composição (Rot 45° seguido de Refl Eixo X)", 
            "rot45_refl_x.png", label_trans="Rot 45° + Refl X")

"""
análise geométrica (verificação de isometria) -------------------------------------------------------------------------------------------------
"""
# isometrias preservam distâncias e ângulos! verificamos com base nisso
# verificação da distância do lado AB (B-A = Coluna 1 - Coluna 0)
lado_AB_orig = T_orig[:, 1] - T_orig[:, 0]
dist_AB_sq_orig = np.dot(lado_AB_orig, lado_AB_orig)

# verificação no triângulo transformado (usando a rotação 90°)
lado_AB_trans = T_R90[:, 1] - T_R90[:, 0]
dist_AB_sq_trans = np.dot(lado_AB_trans, lado_AB_trans)

print("\n--- Análise Geométrica ---")
print("Isometrias Preservam Distâncias (Lado AB)")
print(f"Distância^2 Original: {dist_AB_sq_orig:.5f}")
print(f"Distância^2 Rotacionada: {dist_AB_sq_trans:.5f}")
print(f"Resultado: {'Preservada' if np.isclose(dist_AB_sq_orig, dist_AB_sq_trans) else 'NÃO Preservada'}")


--- Matrizes de Transformação ---
R_x:
[[ 1  0]
 [ 0 -1]]
R_y_x:
[[0 1]
 [1 0]]
Vetor Translação v:
[[ 2 -1]]

--- Composição de Isometrias ---
Matriz Composta M (R_x @ R_90°):
[[ 0. -1.]
 [-1. -0.]]

--- Análise Geométrica ---
Isometrias Preservam Distâncias (Lado AB)
Distância^2 Original: 4.00000
Distância^2 Rotacionada: 4.00000
Resultado: Preservada
